packages:
  - "."
  - "examples/*"
  - "experiments/json-db/cms"
minimumReleaseAgeExclude:
  - '@thednp/rpc@0.0.13 || 0.1.0 || 0.1.1 || 0.2.0 || 0.3.0 || 0.3.1'
  - '@types/node@26.3.0'
  - '@vitest/coverage-istanbul@5.0.1'
  - '@vitest/mocker@5.0.1'
  - '@vitest/pretty-format@5.0.1'
  - '@vitest/spy@5.0.1'
  - '@vitest/ui@5.0.1'
  - '@vitest/utils@5.0.1'
  - hono@4.13.8
  - vitest@5.0.1
